### ISSUE TITLE
Untergliederung der HTML-Struktur

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#1]
Im Moment ist das gesamte Handbuch eine HTML-Datei. Sollten stattdessen aus den (Unter?)-Kapitel eigene HTML-Seiten werden sie wie bei https://mastering-shiny.org/ oder https://developer.thunderbird.net/ und wenn ja bis zu welcher Ebene?

Die Namen der HTML-Dateien sollten möglichst stabil bleiben, um dauerhaft darauf verlinken zu können.

**Comment by clecle** [comment]
Sehe  auch mit den Routen bzw Ankern (wie es aktuell gelöst ist) großes Potential.
Wenn es einfacher zu handeln ist mit einzelnen Kapiteln, dann gern aufteilen - mMn aber nur die Hauptkapitel - sonst wird es uU zu kleinteilig.

**Comment by nichtich** [comment]
Die Untergliederung erfolgt nun nach den Hauptkapiteln:

* https://pro4bib.github.io/handbuch-it-in-bibliotheken/ (=Einleitung)
* https://pro4bib.github.io/handbuch-it-in-bibliotheken/management.html
* https://pro4bib.github.io/handbuch-it-in-bibliotheken/anforderungen.html
* ...

 Zusätzlich gibt es für jeden Anhang eine eigene Seite:

* https://pro4bib.github.io/handbuch-it-in-bibliotheken/zielgruppe.html
* https://pro4bib.github.io/handbuch-it-in-bibliotheken/styleguide.html
