### ISSUE TITLE
Spam-Protection für E-Mail-Adressen der beteiligten Autor*innen

### ISSUE THREAD

**Issue by nicolols** [pro4bib/handbuch-it-in-bibliotheken#10]
Die E-Mail-Adressen der Contributors stehen momentan in Plain-Text in den Markdown-Files und den korresponiderenden html-Files.  --> Mechanismen einbauen, dass diese nicht automatisch von Spam-Bots gescrapt werden können oder andere Lösungsmöglichkeit?

**Comment by nichtich** [comment]
Die umwandlung der emailadressen in irgendwas anderes lässt sich automatisch umsetzen aber was soll im HTML stehen?

**Comment by LuisMossburger** [comment]
Ein Klassiker wäre die Darstellung als `vor.name AT provider.de` / `vor-name[at]provider.de` - aber wie sehr das tatsächlich hilft, weiß ich nicht...

**Comment by nichtich** [comment]
done via quarto feature (see generated HTML)
