### ISSUE TITLE
Bilder im Kapitel Kommunikation nach SVG konvertieren

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#100]
- `stufenmodell.png` unter https://it-in-bibliotheken.de/kommunikation.html#einleitung
- `jobmap.svg` unter https://it-in-bibliotheken.de/kommunikation.html#wissensmanagement (ist schon SVG aber Layout sollte passend zu https://it-in-bibliotheken.de/media/tools.svg sein)

**Comment by BarryJive** [comment]
![jobmap](https://github.com/user-attachments/assets/1b6075a2-e07a-4629-96e5-2c88ca76bf90)
Anweisung etwas unklar, Datei auf Schriftart überprüft. Bei weiteren Änderungswünschen bitte spezifizieren.
![stufenmodell](https://github.com/user-attachments/assets/bc5c362e-9a3c-4067-918e-aaafa88dec19)
Als svg, jedoch nur konvertiert, keine optimale Auflösung.

**Comment by slyck** [comment]
Schaut mal, ob das so passt:
![Stufenmodell](https://github.com/user-attachments/assets/0ee54562-220a-4b19-ac2b-52690c50a04d)
