### ISSUE TITLE
Verweise auf Abbildungen

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#11]
Verweise auf Abbildungen ("siehe Abbildung XX") sind noch nicht umgesetzt, bisher steht meist nur "siehe Abbildung" ohne Link.

**Comment by jannabrechmacher** [comment]
Die Abbildungen sollten pro Kapitel durchnummeriert werden, dann kann sichergestellt werden, dass die Zählung jeweils durchgehend ist. 
Ich mache das mal für die jetzt bestehenden Kapitel so.

**Comment by jannabrechmacher** [comment]
Alle Abbildungen in den bestehenden Kapiteln sind pro Kapitel durchnummeriert. Bezüge im Text erfolgen über die Nummern.
