### ISSUE TITLE
Hinweise zur Mitarbeit zusammenführen

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#12]
Im Moment gibt es sowohl einen [Styleguide](styleguide.md) als auch die Datei [CONTRIBUTING.md](CONTRIBUTING.md). Beide ergänzen sich, die Abgrenzung ist aber nicht ganz klar. Wir sollten sie entweder zusammenführen (vermutlich besser) oder klarer abgrenzen. CONTRIBUTING.md enthält mehr technische Angaben, ich denke das kann aber alles als Anhang auch Teil des Buches werden.

**Comment by jannabrechmacher** [comment]
Zusammenführen halte ich auch für sinnvoller. Ich kümmere mich darum.

**Comment by jannabrechmacher** [comment]
Die Inhalte der beiden Dateien sind jetzt in der Contributing-Datei zusammengeführt. Das Styleguide-Kapitel kann im Anhang durch das Contributing-Kapitel ersetzt werden.

Bei der Zusammenführung ist mir etwas aufgefallen:
Im Styleguide steht _Kursive Hervorhebung sollte nur für Namen, Glossareinträge und Zitate verwendet werden._ In der Contributing-Datei steht, dass kursive Hervorhebungen von Glossareinträgen zu Tooltips führen. Wie werden die verschiedenen Kursivierungen technisch unterschieden? Also wie wird dafür gesorgt, dass nur die Glossareinträge Tooltips bekommen?

**Comment by nichtich** [comment]
> Also wie wird dafür gesorgt, dass nur die Glossareinträge Tooltips bekommen?

Abgesehen davon dass das noch nicht technisch umgesetzt ist (#7) wird das so umgesetzt, dass nachgeschaut wird, ob die kursiv gesetzt Zeichenkette im Glossar enthalten ist. Wenn ja, wird es ein Tooltip (Kursivsetzung kann dabei automatisch entfernt werden), wenn nein, bleibt es kursiv.

**Comment by nichtich** [comment]
Danke, Ich bin noch dabei die zusammengeführten Hinweise weiter auszubauen und in an die richtige Stelle zu bringen.

**Comment by nichtich** [comment]
Die technischen Details sind noch unnvollständig, aber erstmal passt es so. Die Version des styleguide bei Google-Docs ist jetzt allerdings nicht mehr sync, das muss ich noch reparieren.

**Comment by jannabrechmacher** [comment]
Ich habe ein Googledoc mit den zusammengeführten Inhalten erstellt. Es heißt contributing.

Am 16. Mai 2022 6:01:29 PM schrieb Jakob Voß ***@***.***>:
