### ISSUE TITLE
Ergänze metadata.yml für Einbindung in OERSI

### ISSUE THREAD

**Issue by acka47** [pro4bib/handbuch-it-in-bibliotheken#120]
Siehe https://oersi.org/resources/pages/de/docs/sources/gitlab_github/

**Comment by nichtich** [comment]
Passt https://github.com/pro4bib/handbuch-it-in-bibliotheken/blob/main/metadata.yml so? Wird erzeugt mit `metadata.pl`, Datum fehlt noch. Siehe auch #62

**Comment by acka47** [comment]
> Passt https://github.com/pro4bib/handbuch-it-in-bibliotheken/blob/main/metadata.yml so?

Das sieht gut aus. Wir probieren es am besten mal. Wenn du am Repo noch das Tag `open-educational-resources` ergänzt, sollte es beim nächsten Lauf eingesammelt werden und wir können mal schauen, ob es wirklich funktioniert.

**Comment by nichtich** [comment]
Unter https://oersi.org/resources?search=%22IT+in+bibliotheken%22 finde ich das Handbuch nicht. Was fehlt?

**Comment by acka47** [comment]
Sieht eigentlich gut aus:

1. Das Tag `open-educational-resources` ist gesetzt.
2. Es gibt eine `metadata.yml`-Datei

Allerdings wurde die `metadata.yml` nicht mit dem [Formular](https://oersi.gitlab.io/metadata-form/metadata-generator.html) generiert, so dass dort wahrscheinlich ein Problem besteht. Ich habe gerade mal genauer hingeschaut und mir ist folgendes aufgefallen:

In https://github.com/pro4bib/handbuch-it-in-bibliotheken/blob/main/metadata.yml stehen ORCIDs im Feld `orcid` und haben nur die rohe ID als Wert. OERSI/AMB macht ja JSON-LD/LOUD und verlangt die ORCID als URI (`https://orcid.org/{id}` im Feld `id`(das ein Alias von `@id` ist).

**Comment by acka47** [comment]
..und auch die Feldnamen für die Namen unterscheiden sich: `family-names`/`given-names` vs. `familyName`/`givenName`. Das sind die schema.org Keys, es wird ja auch am Anfang al `@context` gesetzt.

**Comment by nichtich** [comment]
Das Handbuch ist jetzt indexiert, siehe https://oersi.org/resources/aHR0cHM6Ly9pdC1pbi1iaWJsaW90aGVrZW4uZGUv
