### ISSUE TITLE
Vorschlag zu Bild zu Information Types im Kap. Forschungsnahe Dienste ("Repositorien für Forschungsergebnisse")

### ISSUE THREAD

**Issue by librarysp** [pro4bib/handbuch-it-in-bibliotheken#122]
CC BY png-Datei
![Information_Types](https://github.com/user-attachments/assets/205716ea-ff73-4182-8f63-da65048d0a5e)

**Comment by nichtich** [comment]
Ach das Bild! Danke für's Hochladen, aber ich habe das Feedback bekommen, dass das Bild eher verwirrt als hilfreich ist, deshalb lassen wir es raus.

**Comment by librarysp** [comment]
Alles klar! Ich dachte, es bildet die "heilige Triade" (Text, Daten, Code) zu den Forschungsergebnissen relativ gut ab. Wenn es vewirrt, lassen wir aber natürlich gerne weg.
