### ISSUE TITLE
Vorschlag für neues Bild (Ersatz für @fig-it-zyklus)

### ISSUE THREAD

**Issue by librarysp** [pro4bib/handbuch-it-in-bibliotheken#123]
So ein Bild vektorialisieren ?
Der Zyklus bildet auch Stilllegung bzw. Abschaltung ab (siehe Kommentar im Text). 
![imac-r-d-1600x900-1](https://github.com/user-attachments/assets/f30b4c9c-633a-428c-b641-ef5b7196d560)

**Comment by nichtich** [comment]
Das bisherige Bild finde ich eigentlich besser (mit Pfeilen, nur Text, eine Farbe). Allerdings muss dort die **Ablösung** hinzugefügt werden (wird im Text direkt beim Bezug auf das Bild erwähnt, daher muss es auch ins Bild).
