### ISSUE TITLE
Code-Beispiele im Metadatenkapitel kleinere Schrift

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#129]
Die Code-Beispiele im Metadaten-Kapitel gehen wegen zu langer Zeile über den Zeilenrand. Eine kleinere Schrift würde hier ausreichen.

**Comment by dorian-grosch** [comment]
Fixed by commit 1fd7315c5b0cfa1f2c4daf7516e5a1e40e539b30
