### ISSUE TITLE
Abkürzungsverzeichnis für Druckversion anpassen

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#130]
Im [Abkürzungsverzeichnis](https://it-in-bibliotheken.de/glossar.html) sind viele Abkürzungen mit einer URL hinterlegt, die in der Druckversion zu einer Fußnote wird. Diese Fußnoten erscheinen aus irgend einem Grund nicht im PDF, wären allerdings sowieso unschön in dieser Form. Im Druck sollten die URLs entweder ganz weggelassen werden oder unter der jeweiligen Definition stehen.

**Comment by dorian-grosch** [comment]
Fixed by commit https://github.com/pro4bib/handbuch-it-in-bibliotheken/commit/4cd90ec71ad4e12e8756c1b7b969c70f60b325fd
