### ISSUE TITLE
Anforderungen-Kapitel: Einleitendes Abstract

### ISSUE THREAD

**Issue by jannabrechmacher** [pro4bib/handbuch-it-in-bibliotheken#17]
Zu diesem Kapitel fehlt das einleitende Abstract.

**Comment by nichtich** [comment]
Der Abstract sollte den *Inhalt* des Kapitel zusammenfassen also nicht im Stil "Im Folgenden wird.." sondern als eigenständiger Absatz (siehe https://it-in-bibliotheken.de/management.html)

**Comment by nichtich** [comment]
@clecle Ich habe die Hervorhebung als Infobox wieder rausgenommen, der aktuelle Text ist eine *Einleitung* zum Kapitel aber keine *Zusammenfassung*. Letztere sollte auch für sich stehen können, wenn der Rest des Kapitels Ersatzlos gestrichen wird.

**Comment by jannabrechmacher** [comment]
@nichtich Der Inhalt des Kapitels passt nicht richtig zur Überschrift. Daher haben Clemens und ich die Änderung vorgenommen. Im Kapitel geht es weniger um die Anforderungen als um die Art, wie man die Bedarfe der Nutzer*innen ermitteln und wie man sie in die Entwicklung einbeziehen kann. 
Die Überschrift könnte in einer kurzen Form dann nur "Nutzer*innenorientierte Gestaltung" heißen. Oder "Anfoderungen an Nutzer*innenorientierte Gestaltung"

**Comment by jannabrechmacher** [comment]
Abstract ergänzt, Überschrift angepasst.
