### ISSUE TITLE
BMS-Kapitel: Kurze, zusammenfassende Infoboxen

### ISSUE THREAD

**Issue by jannabrechmacher** [pro4bib/handbuch-it-in-bibliotheken#18]
Zusammenfassung und Ausblick sollte noch abgefasst werden.

**Comment by nichtich** [comment]
Unter https://it-in-bibliotheken.de/bibliotheksmanagementsysteme.html#systemintegration-%C3%BCber-schnittstellen sind auch noch Stichpunkte.

Außerdem wären weitere kurze, zusammenfassende Infoboxen hilfreich, so dass sich das Kapitel leichter überfliegen lässt.

**Comment by jannabrechmacher** [comment]
Danke @clecle, das passt. Damit bleibt für das Issue nur noch der Hinweis auf die Infoboxen.

**Comment by nichtich** [comment]
Das Kapitel könnte sicher noch etwas mehr aufgelockert werden, aber grundsätzlich reicht es.
