### ISSUE TITLE
Offizielle URL

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#2]
Unter welcher URL soll das Buch offiziell veröffentlicht werden?

**Comment by nichtich** [comment]
Die URL sollte nicht nur weiterleiten sondern das handbuch so erreichbar sein, dass keine GitHub-URLs abgerufen werden. Möglichkeiten dazu:

1. Eigene Domain (CNAME DNS-Eintrag) in den GitHub-Settings einstellen
2. Reverse Proxy
3. Dateien lokale installieren (es sind nur statische Dateien)

Variante 1 und 2 erfordert zusätzlich dass irgendwie mit GitHub-Actions das Buch mit quarto gebaut wird. Zum committen durch des gebauten Buches in einen eigenene git-branch müsste irgendwo ein Passwort hintergelgt werden. Die Variante, das Buch lokal zu hosten wäre mir lieber.

**Comment by nichtich** [comment]
@tudomisc hast du einen Vorschlag für eine stabile URL?

**Comment by tudomisc** [comment]
Definiere stabil. Meinst Du eine URL, die einzigartig und noch nicht belegt ist? Oder die technische Infrastruktur dahinter, die noch Jahre die URL hostet?
a) haitbi.de (HAndbuch IT in BIbliotheken), bib-it-buch.de, handbuch-it-bibliotheken.de, it-bib.de, bibliotheks-it.de, ... alles frei und da geht noch einiges
b) Das kann ich nicht garantieren, ich würde die Domain privat reservieren. Wenn ich vor den Bus laufe, habt ihr ein Problem.

**Comment by nichtich** [comment]
Nee, das sollte nicht an einer Person hängen. Ich denke die VZG kann auch über DFN eine .de-Domain anmelden. Ich bin allerdings unschlüssig ob eine eigene Domain besser ist als ein URL-Pfad und/oder Subdomain einer bestehenden Einrichtung (gbv.de, tib.eu, fid-bbi.de, th-wildau.de...) sinnvoller ist.

**Comment by tudomisc** [comment]
Für eine Subdomain einer bestehenden Einrichtung spricht ein Anschein von Seriösität. Dagegen spricht, dass das Werk nicht ein Produkt einer Einrichtung sondern vieler Menschen ist.
Ich tendiere zu einer eigenen URL ohne Institutionsbezug. Man kann bei den beteiligten Einrichtungen Infoseiten dazu bauen, die auf die unabhängige URL verweisen und so die Seriösität erzeugen.

**Comment by nichtich** [comment]
Domain ist registriert, wird noch eingerichtet. Im Header der erzeugten Dateien sollte noch auf die kanonische URL verwiesen werden.

~~~html
<link rel="canonical" href="https://it-iin-bibliotheken.de/${KAPITEL}" />
~~~

**Comment by tudomisc** [comment]
`<link rel="canonical" href="https://it-in-bibliotheken.de/${KAPITEL}" />`
Ein i war zu viel.
