### ISSUE TITLE
Weiterbildungsangebote Data Science nennen?

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#20]
Ich habe die berufsbegleitende Masterstudiengänge Data Science an der HTWK Leipzig und der HdM Stuttgart rausgenommen, da ich nichts Bibliotheks-IT-Spezifisches dazu finden konnte. [Data Science an der HdM Stuttgart](https://www.hdm-stuttgart.de/ds) hat (wie weitere bisher nicht genannte solcher Data Science Studiengänge) anscheinend keinen Bezug zu Bibliotheken. Ich bin sicher dass Data Science praktisch für Bibliotheks-IT ist aber der Bezug ist nicht viel größer als bei allgemeiner Informatik.

**Comment by nicolols** [comment]
Ich unterstütze deine Entscheidung, die traditionellen Data Science-Studiengänge außen vor zu lassen (ja, Informatikstudium hilft immer, reicht aber allein nicht, um sofort in der Bibliotheks-IT durchstarten zu können).

Zur HdM kann ich deine Feststellung bestätigen, da der berufsbegleitende Data Science M.Sc. in der Wirtschaftsinformatik angesiedelt ist. Es gibt dabei meines Wissen keine einzige Überscheidung zur Bibliotheks-IT oder den Informationswissenschaften.

Möglicherweise war bei der HTWK auch der [Bibliotheksinformatik B.Sc.](https://fim.htwk-leipzig.de/studium/bachelorstudiengaenge/informatik/studium-informatik/studium-im-ueberblick/bachelor-bibliotheksinformatik/) gemeint? Soweit ich es verstanden habe, werden aber Bachelor-Studiengänge hier nicht genannt, weil es in dem Abschnitt primär um berufsbegleitende Angebote geht. Vielleicht gibt es ja aber auch FaMIs, die in der Bibliotheks-IT arbeiten und vielleicht einen Bachelor draufsetzen wollen? Vereinzelt gibt es dabei inzwischen auch zunehmend Teilzeit-Möglichkeiten oder das Duale Studium.

Falls noch Bachelor-Studiengänge aufgeführt werden sollen, würde ich diese nennen (alle Vollzeit):
  * Medieninformatik - Studienrichtung Bibliotheksinformatik B.Sc. an der HTWK Leipzig
  * Informationswissenschaften - Schwerpunkt Daten- und Informationsmanagement B.A. an der HdM Stuttgart (Verkürztes Studium für FaMIs und auch Duales Studium möglich)
  * Data und Information Science - Schwerpunkt Data Librarian B.A. an der TH Köln
  * Information Science B.Sc. an der Hochschule Darmstadt
  * Verwaltungsinformatik B.A. an der HWR Berlin (Duales Studium)
  * Information Science B.Sc. an der FH Graubünden (CH) (auch Teilzeit-Studium möglich)

Von den Master-Studiengängen sind eigentlich alle einschlägigen genannt. In meinem Umfeld haben auch noch viele den M.A. LIS der TH Köln, aber ich bin mir nicht sicher, ob der wirklich für die Bibliotheks-IT einschlägig genug ist, auch trotz des [neuen Curriculums](https://www.o-bib.de/bib/article/view/5708/8447). Ähnliches gilt wahrscheinlich für den Information Science Master an der HU Berlin.

Vielleicht wäre es auch noch passend, die Initiative Fortbildung zu nennen? Die bieten auch immer mal wieder Weiterbildungen mit Bibliotheks-IT-Bezug an. Genauso gibt es da aber auch regionale Angebote der Verbünde wie z. B. die Bibliotheksakademie Bayern oder so was, die IT-Fortbildungen anbieten. Hierbei müssten wir eben noch die relevanten Angebote aller Bundesländer zusammentragen, die habe ich auf Anhieb so auch nicht alle parat.

**Comment by nichtich** [comment]
Wenn die [Konferenz der informations- und bibliothekswissenschaftlichen Ausbildungs- und Studiengänge (KIBA)](https://dgi-info.de/wissenschaft-praxis/dgi-fachgruppen/kiba/) eine aktuelle Liste pflegen würde, könnten wir darauf verweisen, die Studiengänge ändern sich ja ständig.
