### ISSUE TITLE
Keine Fußnoten 

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#21]
Anknüpfend and #19 finde ich dass wir ganz auf Fußnoten verzichten sollten und das auch [im Styleguide](https://it-in-bibliotheken.de/mitarbeit.html#schreibweise-fachbegriffe-und-verweise) so festlegen. Alternativen zu Fußnoten sind:

* Literaturangabe
* Glossar-Eintrag
* Inline-Link (einfache URL)

**Comment by jannabrechmacher** [comment]
Das der Hinweis auf den Fußnotenverzicht im Styleguide steht, kann dieser Issue geschlossen werden
