### ISSUE TITLE
Fehlender Bilder

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#22]
In allen Kapiteln gibt es fehlende oder unfertige Bilder (Fotos/Diagramme).

- [ ] [Technische Infrastruktur](https://it-in-bibliotheken.de/infrastruktur.html)
- [ ] [IT-Entwicklung](https://it-in-bibliotheken.de/anforderungen.html)
- [ ] [IT-Management](https://it-in-bibliotheken.de/management.html)
- [ ] [Sicherheit & Datenschutz](https://it-in-bibliotheken.de/sicherheit.html)
- [ ] [Daten & Metadaten](https://it-in-bibliotheken.de/metadaten.html)
- [ ] [Bibliotheksmanagementsysteme](https://it-in-bibliotheken.de/bibliotheksmanagementsysteme.html)
- [ ] [Discovery & Retrieval](https://it-in-bibliotheken.de/discovery.html)
- [ ] [Digitalisierung](https://it-in-bibliotheken.de/digitalisierung.html)
- [ ] [Forschungsnahe Dienste](https://it-in-bibliotheken.de/forschungsnahe-dienste.html)
- [ ] [Kommunikation](https://it-in-bibliotheken.de/kommunikation.html)

**Comment by nichtich** [comment]
Management von IT-Systemen
* [ ] SDLC-Skizze
* [ ] Verweildauer von Bibliothekssystemen
* [ ] Schichtmodell

Anforderungen an Bibliotheks-IT
* [ ] Aus einem [Vortrag zum Scenario-based Design](https://opus4.kobv.de/opus4-bib-info/frontdoor/index/index/docId/3526)
* [ ] Wireframes und Mock-Ups

Bibliotheksmanagementsysteme
* [ ] Matthews und Block

**Comment by elektrobohemian** [comment]
die management-bilder und erst in den anforderungen hatte ich alle heute morgen erstellt und in md eingebunden. vielleicht hat die jemand wieder entfernt oder im konfliktfall abgelehnt?

**Comment by elektrobohemian** [comment]
ps: trifft auch auf meine textanpassungen zu, bitte an alle: holt euch die changes aus dem repo, bevor ihr committet.

**Comment by nichtich** [comment]
Stand Juli 2022 fehlen noch:

[Anforderungen an Bibliotheks-IT](https://it-in-bibliotheken.de/anforderungen.html)

* [ ] Abbildung 2.2: Aus einem [Vortrag zum Scenario-based Design](https://opus4.kobv.de/opus4-bib-info/frontdoor/index/index/docId/3526) - ist noch Platzhalter
* [ ] Wireframes und Mock-Ups

[Bibliotheksmanagementsysteme](https://it-in-bibliotheken.de/bibliotheksmanagementsysteme.html)

* [ ] Evolution der Bibliotheksmanagementsysteme (Matthews und Block) - Bild ist in Englisch und kein SVG, außerdem steht da noch "[TODO: Ins Deutsche adaptieren]"

**Comment by nichtich** [comment]
Bei Diagrammen mit einer Farbe sollte das gleiche Blau verwendet werden: #2780e3

**Comment by nichtich** [comment]
@elektrobohemian Wir haben jetzt [Bildvorgaben](https://it-in-bibliotheken.de/mitarbeit.html#mitarbeit-medien) und schöne Beispiele (siehe https://it-in-bibliotheken.de/kommunikation.html#werkzeuge und https://it-in-bibliotheken.de/bibliotheksmanagementsysteme.html#geschichte-der-bibliotheksmanagementsysteme

Ich schließe dieses Issue, schau dir mal #80, #81, #82, #83 an!
