### ISSUE TITLE
Fußnoten in Literaturangaben umwandeln

### ISSUE THREAD

**Issue by axenzen** [pro4bib/handbuch-it-in-bibliotheken#25]

**Comment by axenzen** [comment]
Fußnoten 1 und 2 sind in Zotero ergänzt (dort habe ich auch noch ein paar andere Änderungen vorgenommen).

Für Fußnote 3 schlage ich folgende Textänderung vor: 

Relevante Katalog-Informationen werden aus möglichst vielen Bibliotheken regelmäßig abgerufen (Harvesting), in ein einheitliches Datenformat übertragen und anschließend als gemeinsamer Index für die Verwendung in spezialisierten Discovery-Systemen angeboten. 

Fußnote 4 kann mE ersatzlos gestrichen werden, da der entsprechende Text bereits verlinkt ist

**Comment by nichtich** [comment]
Es bleiben noch zwei Fußnoten im Anforderungs-Kapitel.

**Comment by jannabrechmacher** [comment]
Im Anforderungskaptiel habe ich keine Fußnoten mehr gesehenn, dafür aber zwei im Management-Kapitel. Die beiden sind noch nicht bei Zotero (da habe ich keinen Account...)

**Comment by axenzen** [comment]
Die beiden FN im Anforderungskapitel würde ich nicht als Literaturangaben aufnehmen, sondern direkt im Text verlinken. 

FN 1: Text "Grundsatzurteil des EuGH" mit URL verlinken

FN 2: Text "zur Bewertung heranziehen" mit URL verlinken
