### ISSUE TITLE
Infobox mit Link auf Umfrage

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#27]
Im Kapitel Hinweise zur Mitarbeit und/oder Einleitung

**Comment by axenzen** [comment]
https://forms.gle/s4nEoHtrjL93pK5i9

**Comment by nichtich** [comment]
Siehe <https://github.com/pro4bib/handbuch-it-in-bibliotheken/blob/main/_umfrage.md>
