### ISSUE TITLE
Literaturverzeichnis von Zotero einbinden

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#3]
Um das Literaturverzeichnis [aus der Zotero-Gruppe](https://www.zotero.org/groups/4673379/it_in_bibliotheken) einzubinden (bzw. die im Text referenzierten Quellen), wird ein Skript benötigt, um das Verzeichnis von zotero.org als BibTeX-Datei herunterzuladen. Ich habe [hier mal gefragt](https://academia.stackexchange.com/questions/184916/automatically-download-zotero-group-library) wie das gehen könnte, kann jemand helfen, vielleicht @nicolols?

**Comment by nicolols** [comment]
Das ist der API-Call für alle Items unserer Zotero-Gruppe im Format BibTeX
https://api.zotero.org/groups/4673379/items?format=bibtex

Nativ ist JSON:
https://api.zotero.org/groups/4673379/items

Doku der API ist hier: https://www.zotero.org/support/dev/web_api/v3/basics

Für den automatisierten Download sollte ein Bash-Skript mit CURL oder in Python mit requests genügen.

**Comment by nichtich** [comment]
Danke!

**Comment by nichtich** [comment]
Nach Änderungen in Zotero kann die Datei in diesem Repository mit `make refs` aktualisiert werden, sie muss anschließend aber noch committed werden, das ließe sich vielleicht noch vereinfachen.
