### ISSUE TITLE
Gleichzeitiges Arbeiten am Text

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#30]
[Dieser Commit](https://github.com/pro4bib/handbuch-it-in-bibliotheken/commit/d2cfd37b59848e823ad77e7e063d1a8cc443e74e) hat versehentlich Inhalt zurückgesetzt, da anscheinend mehrere gleichzeitig per Web-Interface am Text gearbeitet haben. Wenn das häufiger vorkommt, müssen wir auf Pull-Requests umsteigen, statt direkt im main-branch zu editieren.

**Comment by clecle** [comment]
sorry guys. ich hatte im web-FE gearbeitet. WErde meine Änderungen in Zukunft wieder lokal vornehmen. Dann kann das nicht passieren.
