### ISSUE TITLE
Fonts in SVG-Bildern

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#31]
SVG ist grundsätzlich super aber die Schriftarten sehen je nach System unterschiedlich aus. Wie [hier beschrieben](https://stackoverflow.com/questions/58862977/svg-fonts-that-are-safe-to-use-across-platforms) gibt es keine allgemeine Lösung, ich denke aber die [Empfehlungen bei Wikimedia Commons](https://commons.wikimedia.org/wiki/Help:SVG#Font_substitution_and_fallback_fonts) reichen und schlage vor, grundsätzlich `font-family: 'Liberation Sans', Arial, sans-serif` zu verwenden.

**Comment by LuisMossburger** [comment]
Spräche etwas dagegen die Texte in einem SVG-Programm zu Formen zu konvertieren? Dann würde es nämlich schon gleich aussehen und Alternativtexte brauchen wir für Barrierefreiheit sowieso. Übersehe ich etwas, geht es um die Nachnutzbarkeit?

**Comment by nichtich** [comment]
Wenn die Texte einmal als Vektoren vorliegen, lassen sie sich nicht mehr praktikabel ändern. Wir könnten aber die Dateiversion mit Text ebenfalls ins Repository aufnehmen, um bei Bedarf darauf zurückgreifen zu können.

Grundsätzlich sollten eine oder zwei einheitliche Schriftarten verwendet werden, die auch frei verfügbar sind. Ich denke wenn ich mir die Schriften unter Linux installiere, könnte ich die Bilder nachnutzen. Derzeit sind das:

~~~
~/proj/handbuch-it-in-bibliotheken/media $ grep -ho 'font-family:[^;"]\+' *.svg | sort | uniq
font-family: 
font-family:Bitstream Vera Sans
font-family:'HelveticaNeue-Bold', 'Helvetica Neue'
font-family:'HelveticaNeue', 'Helvetica Neue'
font-family: 'information-iconfont'
~~~

**Comment by nichtich** [comment]
Hier ein Beispiel wie es bei mir aussieht. In dem Bild würde ich außerdem die Balken alle linksbündig setzen, so dass es ein Balkendiagram ist statt der umgekehrte Turm von Hanoi :-)

![grafik](https://user-images.githubusercontent.com/299856/170947824-c840a874-2bc1-42e1-b350-dc7e9207a4e4.png)

**Comment by nichtich** [comment]
Wir können Diagramme übrigens auch [mit Mermaid und Graphviz](https://quarto.org/docs/authoring/markdown-basics.html#diagrams) erzeugen, allerdings sieht das nicht immer schön aus.

**Comment by nichtich** [comment]
Im HTML/CSS steht:

        "Source Sans Pro", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";

**Comment by nichtich** [comment]
Erfasst durch eigene Issues.
