### ISSUE TITLE
Abschnitt Haushalt im BMS-Kapitel

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#32]
Unter https://it-in-bibliotheken.de/bibliotheksmanagementsysteme.html#bezahlsysteme steht noch "TODO"

**Comment by jannabrechmacher** [comment]
Überschrift und Todo entfernt (habe keine Möglichkeit gefunden, es "unsichtbar" zu machen). Kann später mit Inhalt wieder ergänzt werden.
