### ISSUE TITLE
Abstract und Description

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#34]
Das Buch braucht noch einen Abstract (1-3 Absätze) und eine `description` (1 Zeile), letztere für den HTML-Meta-Bereich.

**Comment by jannabrechmacher** [comment]
Erster Aufschlag Abstract:
Die Arbeitsabläufe in Biblitoheken werden zu sehr großen Teilen durch IT-Systeme unterstützt. An zentraler Stelle können hier Bibliotheksmanagementsystemesysteme genannt werden, mit denen die Prozesse der Erwerbung, Erschließung und Ausleihe von Bibliotheken unterstützt werden. Auch für die Nutzenden werden verschiedenste IT-gestützte Services bereitgestellt. Vom klassischen Katalog, einem weiteren Modul von Bibliotheksmanagementsystemen, über die klassische Webseite, spezifische Fachportale, Blogs, Webinare bis hin zu Open Access-Repositorien, Forschungsdatenmanagement oder auch Schnittstellen für den Datenaustausch, um nur ein paar Beispiele zu nennen. 
Mit dem zunehmenden Einsatz von IT für die verschiedenen Angebote für Nutzende sowie zur Unterstützung der Arbeitsabläufe in Bibliotheken wächst auch die Bedeutung des Wissens zum Aufbau, Funktion und Betrieb der hier eingesetzten IT-Systeme. Viel Wissen zu diesem Themen ist vorhanden, implizit und explizit. Verteilt in der Praxis, durch die tägliche Anwendung oder Betreuung der Systeme, durch die (Weiter-)Entwicklung von bestehenden oder neuen Bibliotheks-Services, in Lehre und Forschung, in verschiedenen Publikationen. Mit diesem Handbuch-Projekt soll das vorhandene Wissen kollaborativ zusammengetragen und erarbeitet in einen knappen, umfassenden Überblick über die wichtigsten IT-bezogenen Themen in Bibliotheken münden.

**Comment by nichtich** [comment]
Danke, Ich habe description-tags zu den meisten Seiten hinzugefügt. Die description sollte etwa so lang wie ein klassischer Tweet sein (<140 Zeichen) und erscheint bei Suchmaschinen in der Trefferliste und im Buch als Untertitel eines Kapitels.

**Comment by jannabrechmacher** [comment]
Hier ist eine gekürzte Variante für die `description`:

In Bibliotheken gibt es kaum Abläufe, die nicht durch IT unterstützt werden. Entsprechend wächst auch die Bedeutung des Wissens um Funktion und Betrieb der eingesetzten IT-Systeme.

Eine Kürzung des Abstracts würde ich mir für morgen oder Freitag vornehmen.

**Comment by nichtich** [comment]
Description habe ich schon, allerdings auch eher als Zusammenfassung:

> Die wichtigsten Themen zum Einsatz von IT in Bibliotheken: IT-Management, Bibliotheksmanagementsysteme, Softwareentwicklung, Metadaten…

Dieser Satz erscheint auch Google in der Trefferliste und sollte daher sehr knapp und "catchy" sein und die wichtigsten Begriffe enthalten. Bei den Kapiteln derzeit:

Management von IT-Systemen:
> Organisation und Kompetenzen zum sinnvollen Einsatz von IT-Systemen in Bibliotheken

Anforderungen an die IT-Entwicklung:
> Wie muss die IT in Bibliotheken beschaffen sein und mit welchen Methoden lassen sich Bedarfe und Anforderungen ermitteln?

Bibliotheksmanagementsysteme:
> Aufgaben, Bestandteile, Einsatz und Geschichte von Bibliotheksmanagementsystemen (BMS/LMS) von Beschaffung bis Betrieb

Glossar:
> Die wichtigsten Abkürzungen und Begriffe rund um IT in Bibliotheken

**Comment by jannabrechmacher** [comment]
Folgend ein gekürzter Abstract-Vorschlag:

> Die Arbeitsabläufe in Bibliotheken werden überwiegend durch IT-Systeme unterstützt. Zentral ist das Bibliotheksmanagementsystem (BMS), mit dem die Kernprozesse von Bibliotheken unterstützt werden. Neben dem BMS sind Beispiele für weitere IT-gestützte Services der klassische Katalog als BMS-Modul, die Webseite, spezifische Fachportale, Blogs, Webinare, Open Access-Repositorien, Forschungsdatenmanagement oder auch Schnittstellen für den Datenaustausch.
> Ebenso wie der bibliothekarische IT-Einsatz wächst auch die Bedeutung des Wissens zu diesen IT-Systemen. Viel Wissen ist bereits vorhanden, verteilt in der Praxis, in Lehre und Forschung, in verschiedenen Publikationen. Mit diesem Handbuch-Projekt soll das vorhandene Wissen kollaborativ zusammengetragen und erarbeitet in einen knappen, umfassenden Überblick über die wesentlichen IT-bezogenen Themen in Bibliotheken münden.

**Comment by nichtich** [comment]
Danke, ich passe es noch weiter an damit der Abstract eher das Buch und weniger das Buch-Projekt zusammenfast.
