### ISSUE TITLE
Abbildung ETL-Prozess anpassen

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#47]
Die [Abbildung zum ETL-Prozess](https://it-in-bibliotheken.de/metadaten.html#fig-etl) (Grafik von Stefan Lohrum , Lizenz CC-BY) sollte SVG sein und sich mehr am Text orientieren. Es fehlt z.B. der "Arbeitsbereich" und "Transformation engine" sollte raus, da im Text nirgends erwähnt.

Vorgaben siehe https://it-in-bibliotheken.de/mitarbeit.html#mitarbeit-medien

**Comment by MontyBitto** [comment]
Ist jetzt SVG und ist anscheinend überarbeitet worden.
Jetzt überlappen sich aber Buchstaben. Muss auf jeden Fall nochmal überarbeitet werden.

**Comment by nichtich** [comment]
Da im SVG der Text als Schrift eingebunden ist, sieht die Grafik unterschiedlich aus, je nachdem ob die Schriftart lokal vorhanden ist. Die Grafik sollte einmal mit Text in `media/original` und einmal in Kurven umgewandelt in `media` abgelegt werden.
