### ISSUE TITLE
Glossareinträge mit URL automatisch verlinken

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#48]
Wenn ein Begriff im Glossar eine URL hat, sollte im Text oder per Popover die URL als Link angeboten werden.

**Comment by MontyBitto** [comment]
Das ist jetzt möglich. Kann geschlossen werden, wenn ich das nicht missverstanden habe.

**Comment by nichtich** [comment]
Das Glossar enthält URLs aber sie werden nicht im Popover angezeigt sondern nur der Text.
