### ISSUE TITLE
Einleitung der Hauptkapitel vereinheitlichen

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#49]
Alle Hauptkapitel sollten einen 1-Satz-Abstract und eine Zusammenfassung als Infobox haben.

**Comment by jannabrechmacher** [comment]
Bezieht sich das auf die neuen oder auf alle Kapitel, veröffentlicht und neu?

**Comment by nichtich** [comment]
Alle Kapitel sollten mit einer kurzen Zusammenfassung beginnen in der auf die wichtigsten Abschnitte verwiesen wird. Teilweise ist das im Moment eine Infobox, teilweise normaler Fließtext, teilweise keins von beiden.
