### ISSUE TITLE
Chatbots

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#58]
Chatbots sind bisher nicht erwähnt, würden in den Abschnitt [Dienste für Nutzer*innen](https://it-in-bibliotheken.de/infrastruktur.html#dienste-f%C3%BCr-nutzerinnen) passen.

**Comment by MontyBitto** [comment]
Sind jetzt kurz in [Künstliche Intelligenz](https://it-in-bibliotheken.de/metadaten.html#k%C3%BCnstliche-intelligenz) erwähnt. Der Abschnitt ist auch in #60.
Kann mit Sicherheit noch mehr für beide Themen sein.
