### ISSUE TITLE
Publikation mit DOI

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#61]
Es wäre schön wenn das Handbuch eine DOI bekommt. Da sich das Handbuch ändert, sollten [versionierte DOIs](https://support.datacite.org/docs/versioning) verwendet werden (eine DOI leitet auf die aktuelle Version, zusätzliche DOIs leiten auf versionierte Snapshots). Dazu benötigen wird:

- eine DOI Registrierungsstelle bei der freie URLs eingetragen werden können (kein Repository). Die VZG arbeitet bereits mit verschiedenen Registrierungsstellen (TIB, SUB, GESIS...) zusammen. DOI Vergabestelle ist in allen Fällen DataCite. 
- #14
- #62

Alternativ wäre es auch möglich, die Handbuch-Dateien einfach bei Zenodo hochzuladen (geht sogar automatisch), allerdings geht die DOI dann immer auf Zenodo statt auf die Webansicht, was ziemlich unpraktisch ist. Für eine Druckversion (PDF) könnte es aber ausreichen.

Davon unabhängig könnten wir auch andere Identifier vergeben (Handle, URN, IPFS, DID...). Für URN reicht vermutlich #63.

**Comment by michael-voss-54** [comment]
Ich halte die Vergabe einer versionierten DIO für sinnvoll. Als Registrierungsstelle bietet sich die TIB  (auch wegen Lambert ;-)  vielleicht an).

**Comment by nichtich** [comment]
Wenn jemand Mitglied bei CrossRef ist (275$/ Jahr) kostet eine Ausgabe 1$ bzw. 3.75$ wenn jedes Kapitel eine eigene DOI bekommt (bzw. etwas weniger wenn wir die Kapitel einzeln versionieren). DataCite und Repositories wie Zenodo sind keine Option, da dort die DOI immer zu einer Landing Page führt.

Quelle: https://www.crossref.org/fees/#content-registration-fees

**Comment by lambo** [comment]
Es können heutzutage auch DOIs für Buchkapitel vergeben werden. Seit dem Metadatenschema 4.4 (Eingeführt in April 2021) kann man als ResourceTypeGeneral bookchapter auswählen. Ihr findet hier einen Überblick über alle Optionen: https://wiki.tib.eu/confluence/display/pid/Resource+Type+General 

„DataCite und Repositories wie Zenodo sind keine Option, da dort die DOI immer zu einer Landing Page führt.“ Ja, eine DataCite-DOI führt zu einer Landing Page. Welche Landing Page definiert der DOI-Registrierende. Wichtig ist, dass die Landing Page eine Zitation, die DOI und den Zugang zum Objekt (in unserem Fall ein Buchkapitel) hat und in unserer Verantwortung liegt. 

(Danke an die PID-Beratung der TIB, die mir hier deutlich weitergeholfen hat...)

**Comment by nichtich** [comment]
Auf dem 3. Booksprint sind wir übereingekommen, dass das Handbuch auch eine DOI bekommen soll.

**Comment by nichtich** [comment]
Issue ist jetzt Teil von #124
