### ISSUE TITLE
Bild Kap. Technische Infrastruktur Bild zu svg konvertieren

### ISSUE THREAD

**Issue by slyck** [pro4bib/handbuch-it-in-bibliotheken#73]

**Comment by BarryJive** [comment]
Ich nehme mal an, dass das die beiden hier waren:
![infrastruktur_hf](https://github.com/user-attachments/assets/f56f9c9f-5be3-4eb2-828e-b0221ef57d40)
![infrastruktur_uhf](https://github.com/user-attachments/assets/742a205d-d4e0-4823-b3cb-3bd3fdaa8db3)
