### ISSUE TITLE
Bild Kap. Anforderungsanalyse Bild 3.2

### ISSUE THREAD

**Issue by slyck** [pro4bib/handbuch-it-in-bibliotheken#81]
Unter https://it-in-bibliotheken.de/anforderungen.html#bedarfsermittlung-mit-personas-und-use-cases Bild von  http://claudia-steinau.de aus https://opus4.kobv.de/opus4-bib-info/frontdoor/index/index/docId/3526 - Rechte klären!

**Comment by nichtich** [comment]
Ist geklärt
