### ISSUE TITLE
Bild Kap. Anforderungsanalyse Bild 3.3 nur als Bsp gedacht - anderes / eigenes Bild? oder ordentlich referenzieren

### ISSUE THREAD

**Issue by slyck** [pro4bib/handbuch-it-in-bibliotheken#82]
Bild https://sbt.blob.core.windows.net/storyboards/e479644d/online-library-system.webp unter
https://it-in-bibliotheken.de/anforderungen.html#storyboards-als-fr%C3%BChe-methode

**Comment by nichtich** [comment]
ist erledigt
