### ISSUE TITLE
Bild Kap. Anforderungsanalyse Bild 3.4 nur als Bsp gedacht - anderes / eigenes Bild? oder ordentlich referenzieren

### ISSUE THREAD

**Issue by slyck** [pro4bib/handbuch-it-in-bibliotheken#83]
https://d3h2k7ug3o5pb3.cloudfront.net/image/2023-02-01/b3796410-a1f5-11ed-91cc-733ac0a0cb68.jpg unter
https://it-in-bibliotheken.de/anforderungen.html#wireframes-und-mock-ups

**Comment by nichtich** [comment]
Matthias Finck hat ein anderes Bild ersetzt, das allerdings auch etwas pixelig ist. Bei Bedarf öffnen wir neues Issue dazu.
