### ISSUE TITLE
Hinweis auf Arbeitskopie in Google Drive

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#9]
Bei jedem Kapitel sollte auf die entsprechende Arbeitskopie in Google Drive zum Kommentieren verlinkt werden. Die links stehen in [_gdrive/chapters.csv](https://github.com/pro4bib/handbuch-it-in-bibliotheken/blob/main/_gdrive/chapters.csv)

**Comment by LuisMossburger** [comment]
Ist erledigt!

**Comment by nichtich** [comment]
Ideal wäre die Links auch auf der HTML-Seite bei den jeweiligen Kapiteln zu platzieren.

**Comment by LuisMossburger** [comment]
Tut mir Leid, damit ich das richtig verstehe: Die jeweiligen Links auch in die Markdowndateien einfügen?

**Comment by nichtich** [comment]
> Tut mir Leid, damit ich das richtig verstehe: Die jeweiligen Links auch in die Markdowndateien einfügen?

Nein, die Links sollten bei der Konvertierung nach HTML aus der Datei [_gdrive/chapters.csv](https://github.com/pro4bib/handbuch-it-in-bibliotheken/blob/main/_gdrive/chapters.csv) gelesen und z.B. im rechten Menü angezeigt werden.

**Comment by nichtich** [comment]
Die aktuelle Lösung ist ein Hack aber funktioniert (bis auf bei den Kapiteln ohne Zwischenüberschriften, wegen eines [quasi-bugs in quarto](https://github.com/quarto-dev/quarto-cli/issues/852)):

![grafik](https://user-images.githubusercontent.com/299856/168054399-45b06602-7862-4eae-8d4b-8e2fc851a4e1.png)
