### ISSUE TITLE
SVG-Bild im Kapitel Forschungsnahe Dienste anpassen

### ISSUE THREAD

**Issue by nichtich** [pro4bib/handbuch-it-in-bibliotheken#99]
Datei `media/fd-lifecycle.svg` unter https://it-in-bibliotheken.de/forschungsnahe-dienste.html#forschungsdatenmanagement (zweites Bild!) zuschhneiden und entsprechend https://it-in-bibliotheken.de/mitarbeit.html#mitarbeit-medien anpassen.

**Comment by BarryJive** [comment]
![fd-lifecycle](https://github.com/user-attachments/assets/09cf5ded-826c-4bdd-950f-b0a57518e133)
Farben wurden bereits durch Redaktionsteam angepasst, Bild ist jetzt auf Inhalt zugeschnitten.

**Comment by nichtich** [comment]
Ich hab's noch etwas angepasst, muss so reichen.
